In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:/Users/mkrti/OneDrive/Документы/Python projects/Pandas/Data for pandas/bank_transactions_data_2.csv')

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 0)
pd.set_option('display.expand_frame_repr', False)

In [4]:
df.head

<bound method NDFrame.head of      TransactionID AccountID  TransactionAmount      TransactionDate TransactionType          Location DeviceID      IP Address MerchantID Channel  CustomerAge CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance PreviousTransactionDate
0         TX000001   AC00128              14.09  2023-04-11 16:29:14           Debit         San Diego  D000380  162.198.218.92       M015     ATM           70             Doctor                   81              1         5112.21     2024-11-04 08:08:08
1         TX000002   AC00455             376.24  2023-06-27 16:44:19           Debit           Houston  D000051     13.149.61.4       M052     ATM           68             Doctor                  141              1        13758.91     2024-11-04 08:09:35
2         TX000003   AC00019             126.29  2023-07-10 18:16:08           Debit              Mesa  D000235  215.97.143.157       M009  Online           19            Student                   56      

In [5]:
df.tail()

TransactionID AccountID  TransactionAmount      TransactionDate TransactionType          Location DeviceID      IP Address MerchantID Channel  CustomerAge CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance PreviousTransactionDate
2507      TX002508   AC00297             856.21  2023-04-26 17:09:36          Credit  Colorado Springs  D000625    21.157.41.17       M072  Branch           33             Doctor                  109              1        12690.79     2024-11-04 08:11:29
2508      TX002509   AC00322             251.54  2023-03-22 17:36:48           Debit            Tucson  D000410  49.174.157.140       M029  Branch           48             Doctor                  177              1          254.75     2024-11-04 08:11:42
2509      TX002510   AC00095              28.63  2023-08-21 17:08:50           Debit         San Diego  D000095     58.1.27.124       M087  Branch           56            Retired                  146              1         3382.91     2024-11-04 08:08:39
2510      TX002511   AC00118             185.97  2023-02-24 16:24:46           Debit            Denver  D000634   21.190.11.223       M041  Online           23            Student                   19              1         1776.91     2024-11-04 08:12:22
2511      TX002512   AC00009             243.08  2023-02-14 16:21:23          Credit      Jacksonville  D000215   59.127.135.25       M041  Online           24            Student                   93              1          131.25     2024-11-04 08:07:49

In [6]:
df.shape

(2512, 16)

In [7]:
df.sample(5)

TransactionID AccountID  TransactionAmount      TransactionDate TransactionType       Location DeviceID       IP Address MerchantID Channel  CustomerAge CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance PreviousTransactionDate
2250      TX002251   AC00325             403.63  2023-06-08 16:56:16           Debit      Las Vegas  D000573     96.162.11.85       M042  Branch           31           Engineer                  167              3         3304.02     2024-11-04 08:07:58
411       TX000412   AC00210             242.03  2023-03-13 16:08:41           Debit         Dallas  D000605   219.98.242.240       M014  Online           58           Engineer                  124              1         4382.73     2024-11-04 08:07:12
276       TX000277   AC00403             167.14  2023-04-24 18:33:29           Debit         Denver  D000231   125.89.163.224       M049  Online           76            Retired                   20              1         3877.73     2024-11-04 08:06:26
2270      TX002271   AC00396             789.80  2023-07-10 16:04:39           Debit   Jacksonville  D000271    63.82.133.139       M038     ATM           40             Doctor                   94              1        13948.09     2024-11-04 08:07:32
1310      TX001311   AC00032              52.23  2023-09-11 18:08:19          Credit  San Francisco  D000088  154.138.163.229       M016  Branch           28            Student                   96              1          105.01     2024-11-04 08:08:11

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   TransactionID            2512 non-null   object 
 1   AccountID                2512 non-null   object 
 2   TransactionAmount        2512 non-null   float64
 3   TransactionDate          2512 non-null   object 
 4   TransactionType          2512 non-null   object 
 5   Location                 2512 non-null   object 
 6   DeviceID                 2512 non-null   object 
 7   IP Address               2512 non-null   object 
 8   MerchantID               2512 non-null   object 
 9   Channel                  2512 non-null   object 
 10  CustomerAge              2512 non-null   int64  
 11  CustomerOccupation       2512 non-null   object 
 12  TransactionDuration      2512 non-null   int64  
 13  LoginAttempts            2512 non-null   int64  
 14  AccountBalance          

In [9]:
df.describe()

TransactionAmount  CustomerAge  TransactionDuration  LoginAttempts  AccountBalance
count        2512.000000  2512.000000          2512.000000    2512.000000     2512.000000
mean          297.593778    44.673965           119.643312       1.124602     5114.302966
std           291.946243    17.792198            69.963757       0.602662     3900.942499
min             0.260000    18.000000            10.000000       1.000000      101.250000
25%            81.885000    27.000000            63.000000       1.000000     1504.370000
50%           211.140000    45.000000           112.500000       1.000000     4735.510000
75%           414.527500    59.000000           161.000000       1.000000     7678.820000
max          1919.110000    80.000000           300.000000       5.000000    14977.990000

number of instances the value appears

In [10]:
df['CustomerAge'].value_counts

<bound method IndexOpsMixin.value_counts of 0       70
1       68
2       19
3       26
4       26
        ..
2507    33
2508    48
2509    56
2510    23
2511    24
Name: CustomerAge, Length: 2512, dtype: int64>

In [11]:
df.max()

TransactionID                         TX002512
AccountID                              AC00500
TransactionAmount                      1919.11
TransactionDate            2024-01-01 18:21:50
TransactionType                          Debit
Location                            Washington
DeviceID                               D000700
IP Address                      99.205.173.118
MerchantID                                M100
Channel                                 Online
CustomerAge                                 80
CustomerOccupation                     Student
TransactionDuration                        300
LoginAttempts                                5
AccountBalance                        14977.99
PreviousTransactionDate    2024-11-04 08:12:23
dtype: object

In [19]:
filename = ("c:/Users/mkrti/OneDrive/Документы/Python projects/Pandas/Data for pandas/data1.csv")

data = np.loadtxt(filename, delimiter = ",", skiprows=1)
print(data)

[[ 1. 10. 30.]
 [ 2. 20. 30.]
 [ 3. 30. 40.]
 [ 3. 40. 30.]
 [ 2. 30. 40.]
 [ 7. 10. 23.]
 [ 3. 20. 22.]
 [ 8. 20. 11.]
 [ 2. 30.  2.]]


In [ ]:
data = np.random.random(size=(5,3))

df1 = 

array([[0.43339256, 0.81990255, 0.22152528],
       [0.23806701, 0.3278889 , 0.15201438],
       [0.25356694, 0.9033204 , 0.0966956 ],
       [0.84034871, 0.72371916, 0.62150586],
       [0.61525132, 0.86136542, 0.84513863]])